.SILENT: # Used to avoid showing the commands executed
.DEFAULT_GOAL: init # Set the default goal to init

########################################
#          INITIALIZE PROJECT          #
########################################

.PHONY: init
init: # Initialize the project by getting the dependencies and generating the files
	make -s get
	make -s gen

.PHONY: reset
reset: # Reset the project by cleaning the project and initializing it
	make -s clean
	make -s init

#################################
#          PUB RELATED          #
#################################

.PHONY: get
get: # Get the dependencies for the project
	flutter pub get

.PHONY: outdated
outdated: # Check for outdated flutter packages
	flutter pub outdated

#############################################
#          CODE GENERATION RELATED          #
#############################################

.PHONY: gen
gen: # Generate all the files needed for the project
	make -s gen-clean
	dart run build_runner build --delete-conflicting-outputs

.PHONY: gen-watch
gen-watch: # Generate all the files needed for the project and watch for changes to regenerate them
	dart run build_runner watch --delete-conflicting-outputs

.PHONY: gen-clean
gen-clean: # Remove all the files generated by the project
	find . -type f -name '*.g.dart' -delete
	rm -rf lib/generated

##############################
#          CLEANING          #
##############################

.PHONY: clean
clean: # Remove all the files generated by the project and delete the flutter cache
	flutter clean
	make -s gen-clean

####################################
#          BUILD / DEPLOY          #
####################################

.PHONY: linux
linux: # Build the app for linux platform
	flutter build linux

.PHONY: android
android: # Build the app for android platform
	flutter build apk

.PHONY: web
web: # Build the app for web platform and deploy to firebase hosting
	flutter build web
	firebase deploy --only hosting

.PHONY: all
all: # Build the app for all supported platforms (linux, Android, web)
	make -s reset
	make -s linux
	make -s android
	make -s web

##########################
#          HELP          #
##########################

.PHONY: help
help: # Show help for each of the Makefile recipes.
	@grep -E '^[a-zA-Z0-9 -]+:.*#'  Makefile | while read -r l; do printf "\033[1;32m$$(echo $$l | cut -f 1 -d':')\033[00m:$$(echo $$l | cut -f 2- -d'#')\n"; done